version: "3.9"

services:
  db:
    image: db
    restart: always
    container_name: db
    build:
      context: .
      target: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=game
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

