version: "3.9"

services:
  eryantis-db:
    image: eryantis-db
    restart: always
    container_name: eryantis-db
    build:
      context: .
      target: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=game
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  eryantis-db-test:
    image: eryantis-db
    restart: always
    container_name: eryantis-db-test
    build:
      context: .
      target: db
    environment:
      - POSTGRES_DB=eriantys_test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"